#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { isAbsolute, relative, resolve, join } from "node:path";

const root = resolve(import.meta.dirname, "../../..");
const generatedRoot = join(root, "build");
const data = join(root, "data");
const outputIndex = process.argv.indexOf("--output");
const outputArg = outputIndex === -1 ? "build/resume" : process.argv[outputIndex + 1];
if (!outputArg) throw new Error("--output requires a path");
const output = resolve(root, outputArg);
const outputRelativeToBuild = relative(generatedRoot, output);
if (outputRelativeToBuild.startsWith("..") || isAbsolute(outputRelativeToBuild)) {
    throw new Error("Output must be inside the generated build directory");
}
if (existsSync(output)) rmSync(output, { recursive: true });
mkdirSync(join(output, "sections"), { recursive: true });
mkdirSync(join(output, "generated"));
mkdirSync(join(output, "images"));

const read = (name) => JSON.parse(readFileSync(join(data, name), "utf8"));
const tex = (value) =>
    String(value)
        .replaceAll("\\", "\\textbackslash{}")
        .replaceAll("&", "\\&")
        .replaceAll("%", "\\%")
        .replaceAll("#", "\\#")
        .replaceAll("_", "\\_")
        .replaceAll("{", "\\{")
        .replaceAll("}", "\\}");
const yearRange = (start, end) => `${start.slice(0, 4)}--${end ? end.slice(0, 4) : "Present"}`;
const experiences = read("experiences.json");
const education = read("education.json");
const certifications = read("certifications.json");
const byTitle = Object.fromEntries(certifications.map((item) => [item.title, item]));
const required = [
    "Azure Developer Associate",
    "Professional Scrum Developer I",
    "GitHub Actions",
    "GitHub Copilot",
    "GitHub Agentic AI Developer",
];
const missing = required.filter((title) => !byTitle[title]);
if (missing.length) throw new Error(`Missing canonical certifications: ${missing.join(", ")}`);
const current = experiences[0];
const command = (name, value) => `\\newcommand{\\${name}}{${tex(value)}}`;
const facts = [
    "% Generated by scripts/build-resume.mjs; do not edit.",
    command("ExperienceCurrentTitle", current.name),
    command("ExperienceCompany", current.company.name),
    command("ExperienceCurrentDates", yearRange(current.start, current.end)),
    command("EducationName", education.name),
    command("EducationUniversity", education.University),
    command("EducationDates", education.details[1].replace(/\s*–\s*/, "--")),
    command("CertificationAzureDeveloper", byTitle["Azure Developer Associate"].title),
    command("CertificationAzureDate", byTitle["Azure Developer Associate"].date.slice(0, 4)),
    command("CertificationAzureUrl", byTitle["Azure Developer Associate"].url),
    command("CertificationScrum", byTitle["Professional Scrum Developer I"].title),
    command("CertificationScrumDate", byTitle["Professional Scrum Developer I"].date.slice(0, 4)),
    command("CertificationScrumUrl", byTitle["Professional Scrum Developer I"].url),
    command("CertificationGithubActions", byTitle["GitHub Actions"].title),
    command("CertificationGithubActionsDate", byTitle["GitHub Actions"].date.slice(0, 4)),
    command("CertificationGithubActionsUrl", byTitle["GitHub Actions"].url),
    command("CertificationGithubCopilot", byTitle["GitHub Copilot"].title),
    command("CertificationGithubCopilotDate", byTitle["GitHub Copilot"].date.slice(0, 4)),
    command("CertificationGithubCopilotUrl", byTitle["GitHub Copilot"].url),
    command("CertificationGithubAgentic", byTitle["GitHub Agentic AI Developer"].title),
    command(
        "CertificationGithubAgenticDate",
        byTitle["GitHub Agentic AI Developer"].date.slice(0, 4),
    ),
    command("CertificationGithubAgenticUrl", byTitle["GitHub Agentic AI Developer"].url),
    command(
        "CertificationGithubCopilotCore",
        byTitle["GitHub Copilot: Core Skills & Application Delivery Credential"].title,
    ),
    command(
        "CertificationGithubCopilotCoreDate",
        byTitle["GitHub Copilot: Core Skills & Application Delivery Credential"].date.slice(0, 4),
    ),
    command(
        "CertificationGithubCopilotCoreUrl",
        byTitle["GitHub Copilot: Core Skills & Application Delivery Credential"].url,
    ),
    "",
].join("\n");
cpSync(join(root, "resume.tex"), join(output, "resume.tex"));
for (const name of [
    "summary.tex",
    "experience.tex",
    "skills.tex",
    "languages.tex",
    "education.tex",
    "certifications.tex",
])
    cpSync(join(root, "sections", name), join(output, "sections", name));
cpSync(join(root, "fonts"), join(output, "fonts"), { recursive: true });
cpSync(join(root, "images", "avatar.png"), join(output, "images", "avatar.png"));
writeFileSync(join(output, "generated", "facts.tex"), facts);
let lastError;
for (let attempt = 1; attempt <= 3; attempt += 1) {
    try {
        execFileSync("tectonic", ["--chatter", "minimal", "--outdir", output, join(output, "resume.tex")], {
            stdio: "inherit",
        });
        execFileSync(process.execPath, [join(root, "scripts", "validate-resume.mjs"), join(output, "resume.pdf")], {
            stdio: "inherit",
        });
        execFileSync(
            "pdftoppm",
            ["-f", "1", "-singlefile", "-png", "-r", "150", join(output, "resume.pdf"), join(output, "resume-preview")],
            { stdio: "inherit" },
        );
        lastError = undefined;
        break;
    } catch (error) {
        lastError = error;
        if (attempt < 3)
            console.warn(
                `Resume build attempt ${attempt} failed; retrying to recover transient renderer or bundle errors.`,
            );
    }
}
if (lastError) throw lastError;
